name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Conditions
      id: test-conditions
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Conditions
        setup-command: npm install
        command: npm run test run conditions
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CONDITIONS_RESULTS: "${{steps.test-conditions.outputs.result}}"
      with:
        runners: test-conditions
