name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test maths
      id: test-maths
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test maths
        setup-command: npm install
        command: npm run test run maths
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-MATHS_RESULTS: "${{steps.test-maths.outputs.result}}"
      with:
        runners: test-maths
